# Generated by Django 4.0.4 on 2022-04-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisormenuitem',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
