# Generated by Django 4.0.4 on 2022-04-25 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_menu', '0002_supervisormenuitem_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisormenuitem',
            name='parent',
        ),
        migrations.CreateModel(
            name='SupervisorSubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(help_text='Sub menu item text', max_length=20)),
                ('url', models.CharField(max_length=40)),
                ('position', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='supervisor_menu.supervisorsubmenuitem')),
            ],
        ),
    ]
