# Generated by Django 4.0.4 on 2022-04-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_menu', '0003_remove_supervisormenuitem_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorsubmenuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='supervisor_menu.supervisormenuitem'),
        ),
    ]
